add functions to test_SimulatedTimeSeries.py
CSE-O1/cs207project pull request #10
Opened 2016-11-01 20:12 UTC by minglong-cse2016

Updates for test_SimulatedTimeSeries.py:

1. added test_type(), test_str(), test_repr(), test_mean_std to the test module.
2. tested all existing test functions
3. added docstrings to all existing functions
4. Please double check if the test criteria for test_mean_std is good.

2016-11-01 20:26 UTC, lyuqin requested changes

2016-11-01 20:26 UTC, lyuqin commented on timeseries/tests/test_SimulatedTimeSeries.py
> +""" test code for SimulatedTimeSeries
I am not quite sure whether the doc should be put ahead of imports or not. Double check this format (or use pylint)

2016-11-01 20:26 UTC, lyuqin commented on timeseries/tests/test_SimulatedTimeSeries.py
> +    A function to generate normally distributed data with mean of 1e4 and standard deviation m
"with ... standard deviation m", but it seems that the std here is in_std, not m?

2016-11-01 20:26 UTC, lyuqin commented on timeseries/tests/test_SimulatedTimeSeries.py
> +    A function to test online_mean and online_std using data size 1e5 and chunk size 9e4
chunk size seems way tooooooo big, why not use chunk size < 10?

2016-11-01 20:26 UTC, lyuqin commented on timeseries/tests/test_SimulatedTimeSeries.py
> +    A function to test online_mean and online_std using data size 1e5 and chunk size 9e4
I suggest data size = 100, chunk size = 5

2016-11-01 20:40 UTC, minglong-cse2016 commented on timeseries/tests/test_SimulatedTimeSeries.py
> +    A function to generate normally distributed data with mean of 1e4 and standard deviation m
Will correct the variable name.

2016-11-01 20:41 UTC, minglong-cse2016 commented on timeseries/tests/test_SimulatedTimeSeries.py
> +""" test code for SimulatedTimeSeries
Pylint seems to suggest this format, thanks!

2016-11-02 00:20 UTC, lyuqin approved these changes

2016-11-02 00:46 UTC, merged